name: PR Preview

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy-preview:
    if: github.event.action != 'closed'
    concurrency:
      group: gh-pages-deploy
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create PR preview folder
        run: |
          mkdir -p pr-preview/pr-${{ github.event.number }}
          rsync -av --exclude=pr-preview --exclude=.git --exclude=.github ./ pr-preview/pr-${{ github.event.number }}/
          touch pr-preview/.nojekyll

      - name: Deploy to gh-pages (preview)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pr-preview
          publish_branch: gh-pages
          keep_files: true

      - name: Print Preview URL
        env:
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          PR: ${{ github.event.number }}
        run: |
          echo "📦 Preview URL: https://${OWNER}.github.io/${REPO}/pr-${PR}/"

      - name: Comment with preview URL
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request.number;
            const base = `https://${context.repo.owner}.github.io/${context.repo.repo}`;
            const url = `${base}/pr-${pr}/`;
            github.rest.issues.createComment({
              issue_number: pr,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `📦 Preview available: [View it here](${url})`
            });

  cleanup-preview:
    if: github.event.action == 'closed'
    concurrency:
      group: gh-pages-deploy
      cancel-in-progress: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Remove PR preview folder
        run: |
          rm -rf pr-${{ github.event.number }}
          touch .nojekyll

      - name: Commit and push cleanup
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Cleanup preview for PR #${{ github.event.number }}" || echo "Nothing to commit"
          git push origin gh-pages
